# fly.toml app configuration file generated for personal-website-dev on 2023-12-26T19:44:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "personal-website-dev"
primary_region = "mia"

[build]

[deploy]
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
