export const projects: Project[] = [
    {
        id: '1',
        year: 2023,
        month: 8,
        client: 'Personal',
        title: 'ChatUI',
        description: 'UI for managing chats with LLMs',
        href: 'https://github.com/jedwards1230/chat',
        tags: [
            'TypeScript',
            'NextJS',
            'TailwindCSS',
            'OpenAI API',
            'Supabase',
            'Oauth',
        ],
        showcase: true,
        img: 'https://raw.githubusercontent.com/jedwards1230/chat/main/screenshots/screenshot-0.png',
    },
    {
        id: '2',
        year: 2023,
        month: 6,
        client: 'Personal',
        title: 'SearchAI',
        description: 'AI assisted search engine',
        href: 'https://github.com/jedwards1230/search',
        tags: [
            'TypeScript',
            'NextJS',
            'TailwindCSS',
            'OpenAI API',
            'Langchain',
            'Supabase',
        ],
        showcase: true,
        img: 'https://raw.githubusercontent.com/jedwards1230/search/main/home.png',
    },
    {
        id: '3',
        year: 2022,
        month: 5,
        client: 'Personal',
        title: 'go-kerbal',
        description: 'CLI for managing Kerbal Space Program mods',
        href: 'https://github.com/jedwards1230/go-kerbal',
        tags: ['Go', 'CLI'],
        showcase: true,
        img: 'https://raw.githubusercontent.com/jedwards1230/go-kerbal/main/extras/screenshots/main.png',
    },
    {
        id: '4',
        year: 2023,
        month: 8,
        client: 'Personal',
        title: 'Personal Website',
        description: 'My corner of the internet',
        href: 'https://github.com/jedwards1230/personal-website',
        tags: ['TypeScript', 'NextJS', 'TailwindCSS'],
        showcase: true,
        img: 'https://raw.githubusercontent.com/jedwards1230/personal-website/main/screenshot.png',
    },
    {
        id: '5',
        year: 2022,
        month: 12,
        client: 'Atlantis Health',
        title: 'Adele',
        description: 'AI Powered Medication Assistant',
        tags: [
            'TypeScript',
            'NextJS',
            'TailwindCSS',
            'IBM Watson',
            'AWS',
            'Playwright',
            'Figma',
        ],
    },
    {
        id: '6',
        year: 2022,
        month: 11,
        client: 'Atlantis Health',
        title: 'Learning Modules',
        description: 'Linear Learning Modules for Patients',
        tags: ['TypeScript', 'React', 'TailwindCSS', 'Playwright', 'Figma'],
    },
    {
        id: '7',
        year: 2023,
        month: 7,
        client: 'Atlantis Health',
        title: 'Email Templates',
        description: 'Email Templates for Patient Outreach',
        tags: ['HTML', 'CSS', 'Figma'],
    },
    {
        id: '8',
        year: 2023,
        month: 8,
        client: 'Atlantis Health',
        title: 'Static Pages',
        description: 'Static Pages for Patient Outreach, Marketing, and Sales',
        tags: ['HTML', 'TailwindCSS', 'TypeScript', 'Figma'],
    },
    {
        id: '9',
        year: 2023,
        month: 6,
        client: 'Atlantis Health',
        title: 'Patient Portal',
        description: 'Patient Portal for managing treatment',
        tags: [
            'TypeScript',
            'Python',
            'NextJS',
            'TailwindCSS',
            'AWS',
            'Playwright',
            'Figma',
        ],
    },

    {
        id: '10',
        year: 2022,
        month: 8,
        client: 'Personal',
        title: 'Cars',
        description: 'A small game for learning ML basics',
        href: 'https://github.com/jedwards1230/cars',
        tags: ['TypeScript', 'NextJS', 'TailwindCSS'],
    },
    {
        id: '11',
        year: 2022,
        month: 8,
        client: 'Personal',
        title: 'nnjs',
        description: 'A small library for learning ML basics',
        href: 'https://github.com/jedwards1230/nnjs',
        tags: ['TypeScript'],
    },
    {
        id: '12',
        year: 2022,
        month: 8,
        client: 'Personal',
        title: 'Leetcode Timer',
        description: 'Firefox extension for timing LeetCode problems',
        href: 'https://github.com/jedwards1230/leetcode-timer',
        tags: ['TypeScript', 'HTML', 'CSS', 'Webpack', 'Browser Extensions'],
    },
    {
        id: '13',
        year: 2022,
        month: 8,
        client: 'Personal',
        title: 'Daily arXiv',
        description: 'Quickly browse ArXiv by date and subject',
        href: 'https://github.com/jedwards1230/dailyarxiv',
        tags: ['TypeScript', 'NextJS', 'TailwindCSS'],
    },
];

export const experience: Experience[] = [
    {
        title: 'Full Stack Developer',
        company: 'Atlantis Health',
        period: '08/2021 - Present',
        description: [
            'Delivered full-stack applications for multiple clients using agile methodologies and led the development of a large-scale NextJs website.',
            "Implemented IBM Watson's NLP capabilities in a patient treatment support application and improved legacy app performance significantly.",
            'Enhanced CI/CD deploy times on AWS infrastructure and fostered effective teamwork leading to projects completion ahead of schedule.',
        ],
        tags: [
            'TypeScript',
            'NextJs',
            'Python',
            'SQL',
            'AWS',
            'TailwindCSS',
            'IBM Watson',
            'Asana',
        ],
    },
    {
        title: 'Product Support Specialist',
        company: 'VantagePoint AI',
        period: '01/2021 - 11/2021',
        description: [
            'Maintained knowledge of AI software platform and identified bugs, enhancing product stability.',
            'Resolved support tickets with exceptional customer service and coordinated with Software Potential for customer info management.',
            'Assisted users in troubleshooting software issues and created helpful knowledge base articles.',
        ],
        tags: ['Bug Reports', 'Salesforce', 'Software Potential'],
    },
    {
        title: 'Entertainment Technician',
        company: 'Freelance',
        period: '03/2015 - 05/2022',
        description: [
            'Led and trained crews for events and resolved technical issues.',
            'Steered problem-solving initiatives during productions to ensure smooth events.',
            'Participated in various aspects of production.',
        ],
        tags: ['Leadership', 'Project Planning', 'Troubleshooting'],
    },
];
