name: Docker Image CI

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-session-name: gh-action-docker-build
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Retrieve Secrets from AWS Secrets Manager
              run: |
                  export NEXT_PUBLIC_URL=$(aws secretsmanager get-secret-value --secret-id next_public_url --query SecretString --output text)
                  export PLAUSIBLE_API_KEY=$(aws secretsmanager get-secret-value --secret-id plausible_api_key --query SecretString --output text)
                  export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id database_url --query SecretString --output text)
                  export DIRECT_URL=$(aws secretsmanager get-secret-value --secret-id direct_url --query SecretString --output text)

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            # Build Main image
            - name: Build, tag, and push App image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: personal-website
                  IMAGE_TAG: ${{ github.sha }}
                  NEXT_PUBLIC_URL: ${{ env.NEXT_PUBLIC_URL }}
                  PLAUSIBLE_API_KEY: ${{ env.PLAUSIBLE_API_KEY }}
                  DATABASE_URL: ${{ env.DATABASE_URL }}
                  DIRECT_URL: ${{ env.DIRECT_URL }}
              run: |
                  docker build \
                    --build-arg NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL} \
                    --build-arg PLAUSIBLE_API_KEY=${PLAUSIBLE_API_KEY} \
                    --build-arg DATABASE_URL=${DATABASE_URL} \
                    --build-arg DIRECT_URL=${DIRECT_URL} \
                    --cache-from=type=local,src=/tmp/.buildx-cache \
                    -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

            - name: Download task definition
              run: |
                  aws ecs describe-task-definition \
                    --task-definition personal-website \
                    --query taskDefinition | \
                    jq 'del(.compatibilities, .taskDefinitionArn, .requiresAttributes, .revision, .status, .registeredAt, .registeredBy)' \
                    > task-definition.json

            # Assign Main image
            - name: Fill in the new App image ID in the Amazon ECS task definition
              id: task-def
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                  task-definition: task-definition.json
                  container-name: personal-website
                  image: ${{ steps.build-image.outputs.image }}

            - name: Deploy Amazon ECS task definition
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                  task-definition: ${{ steps.task-def.outputs.task-definition }}
                  service: personal-website
                  cluster: personal-website
                  wait-for-service-stability: false
