-- AlterTable
ALTER TABLE "About" ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "github" DROP DEFAULT,
ALTER COLUMN "linkedin" DROP DEFAULT,
ALTER COLUMN "location" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT;
